# Generated by Django 6.0.6 on 2026-07-03 00:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline')], default='active', max_length=20)),
                ('stream_url', models.URLField(blank=True, help_text='Mock stream URL for the frontend to display', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('person_detected', 'Person Detected'), ('motion', 'Motion Detected'), ('vehicle', 'Vehicle Detected'), ('license_plate', 'License Plate Read'), ('alert', 'Security Alert')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence', models.FloatField(default=0.95, help_text='Confidence score from the CV model (0.0 to 1.0)')),
                ('details', models.TextField(blank=True, help_text='Additional event details (JSON or text)')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cameras.camera')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
